language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
install: 
  - pip install ply
  - pip install coveralls
script:
  - coverage run --source=xtuml,bridgepoint setup.py test
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
